console.log('[Start]!');

try
{
	foo();
}
catch (error)
{
	console.error('Error occured:', error);
}

console.log('[End]');